/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2020-03-02 22:45:43 
*/
import { INetworkPlayer, IPacketHeader } from "modloader64_api/NetworkHandler";
import * as API from 'MajorasMask/API/Imports';

export interface IPuppetOverlord {
    readonly current_scene: number;
    postinit(): void;
    localPlayerLoadingZone(): void;
    localPlayerChangingScenes(entering_scene: number, form: API.MMForms): void;
    registerPuppet(player: INetworkPlayer): void;
    unregisterPuppet(player: INetworkPlayer): void;
    changePuppetScene(player: INetworkPlayer, entering_scene: number, form: API.MMForms): void;
    processNewPlayers(): void;
    processAwaitingSpawns(): void;
    lookForMissingOrStrandedPuppets(): void;
    sendPuppetPacket(): void;
    processPuppetPacket(packet: IPacketHeader): void;
    generateCrashDump(): void;
    onTick(): void;
}
