/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2020-03-02 22:34:46 
*/
import { IOOTCore } from "modloader64_api/OOT/OOTAPI";
import { IModLoaderAPI } from "modloader64_api/IModLoaderAPI";
import { MMCore } from "@MMARO/MMAPI/Core";
import Vector3 from "modloader64_api/math/Vector3";

export interface IPuppetData {
    pointer: number;
    ModLoader: IModLoaderAPI;
    core: MMCore;
    pos: Buffer;
    rot: Buffer;
    toJSON(): any;
}
